[tool.poetry]
name = "pantheon"
version = "1.0.0"
description = ""
authors = ["Zhifang Ye <zhifang.ye.fghm@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.*"
numpy = "*"
pandas = "*"
scipy = "*"
statsmodels = "*"
scikit-learn = ">=0.24"
scikit-image = "*"
ipython = "*"
ipywidgets = "*"
jupyterlab = "*"
jupyterlab-lsp = "*"
python-lsp-server = {version = "*", extras = ["all"]}
xeus-python = "*"
jupyterlab_code_formatter = "*"
jupytext = "*"
nbdime = "*"
matplotlib = "*"
seaborn = "*"
plotly = "*"
kaleido = "!=0.2.1.post1"
bokeh = "*"
lets-plot = "*"
vtk = "9.0.1"
mayavi = "*"
h5py = "*"
black = "*"
joblib = "*"
memory-profiler = "*"
pyjanitor = "*"
cookiecutter = "*"
yellowbrick = "*"
bigmpi4py = "*"
ftfy = "*"
rpy2 = "*"
radian = "*"
xgboost = "*"
torch = ">=1.8.0"
torchvision = "*"
timm = "*"
tensorflow = ">=2.6.0"
tensorflow-probability = "*"
umap-learn = "*"
gensim = "*"
datalad = "*"
nilearn = "*"
nipype = "*"
brainiak = "*"
mne = "*"
pymvpa2 = "*"
brainspace = "*"
neuropythy = "*"
pysurfer = {version = "*", extras = ["save_movie"]}
heudiconv = "*"
pybids = "*"
bidscoin = "*"
antspyx = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
